version: "1"
rules:
  - base: main
    upstream: sequelize:main
    mergeMethod: merge
    conflictReviewers:
      - tvaamorim
  - base: v6
    upstream: sequelize:v6
    mergeMethod: merge
    conflictReviewers:
      - tvaamorim
